version: "3.9"

services:
  app:
    image: pavan490/test-demo   # Your Docker Hub image name
    container_name: demo-longbow-app
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:mysql://longbowdb.cxrtqrfmnb10.ap-south-1.rds.amazonaws.com:3306/TESTDEMO?
              createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: india123
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    restart: always
