apiVersion: apps/v1
kind: Deployment
metadata:
  name: demolongbow-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demolongbow
  template:
    metadata:
      labels:
        app: demolongbow
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: demolongbow-app
          image: pavan490/test-demo:latest
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
